// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Controllers.ClientController.Create(LBH.AdultSocialCare.Api.V1.Boundary.Request.ClientsRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{LBH.AdultSocialCare.Api.V1.Boundary.Response.ClientsResponse}}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Controllers.HomeCarePackageController.Create(LBH.AdultSocialCare.Api.V1.Boundary.Request.HomeCarePackageRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{LBH.AdultSocialCare.Api.V1.Boundary.Response.HomeCarePackageResponse}}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Controllers.HomeCarePackageController.Create(LBH.AdultSocialCare.Api.V1.Boundary.Request.HomeCare.HomeCarePackageRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{LBH.AdultSocialCare.Api.V1.Boundary.Response.HomeCarePackageResponse}}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Controllers.HomeCare.HomeCarePackageController.Create(LBH.AdultSocialCare.Api.V1.Boundary.Request.HomeCare.HomeCarePackageRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{LBH.AdultSocialCare.Api.V1.Boundary.Response.HomeCarePackageResponse}}")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Infrastructure.Migrations.SeedData.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Infrastructure.Migrations.InitialMigration.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Infrastructure.Migrations.CreateDayCarePackageOptions.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Infrastructure.Migrations.HomeCareServiceTypeMinutesSeed.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.Migrations.Initial.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.Migrations.SeedUserAndClient.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Infrastructure.Migrations.SeedDayCarePackageStatus.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Infrastructure.Migrations.UpdateReclaimOptionsEntities.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Infrastructure.RequestExtensions.PagedList`1.ToPagedList(System.Collections.Generic.IEnumerable{`0},System.Int32,System.Int32,System.Int32)~LBH.AdultSocialCare.Api.V1.Infrastructure.RequestExtensions.PagedList`1")]
[assembly: SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Infrastructure.RequestExtensions.PagedList`1.ToPagedList(System.Collections.Generic.IEnumerable{`0},System.Int32,System.Int32)~LBH.AdultSocialCare.Api.V1.Infrastructure.RequestExtensions.PagedList`1")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Infrastructure.Migrations.PrimarySupportReasonSeed.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Infrastructure.Migrations.DayCarePackageUpdates.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Infrastructure.Migrations.RoleIdToGuid.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:LBH.AdultSocialCare.Api.V1.Infrastructure.Migrations.RoleIdToGuid.Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
