// <auto-generated />
using System;
using LBH.AdultSocialCare.Api.V1.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LBH.AdultSocialCare.Api.V1.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210420160412_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.Clients", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HackneyId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aee45700-af9b-4ab5-bb43-535adbdcfb80"),
                            AddressLine1 = "Queens Town Road",
                            CreatorId = 0,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 504, DateTimeKind.Unspecified).AddTicks(6812), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfBirth = new DateTime(1990, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 504, DateTimeKind.Unspecified).AddTicks(6820), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Furkan",
                            HackneyId = 66666,
                            LastName = "Kayar",
                            PostCode = "SW11",
                            Town = "London",
                            UpdatorId = 0
                        });
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.DayCarePackage", b =>
                {
                    b.Property<Guid>("DayCarePackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("EscortNeeded")
                        .HasColumnType("bit");

                    b.Property<bool>("Friday")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFixedPeriodOrOngoing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsThisAnImmediateService")
                        .HasColumnType("bit");

                    b.Property<bool>("IsThisUserUnderS117")
                        .HasColumnType("bit");

                    b.Property<bool>("Monday")
                        .HasColumnType("bit");

                    b.Property<string>("NeedToAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<bool>("Saturday")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<bool>("Sunday")
                        .HasColumnType("bit");

                    b.Property<int>("TermTimeConsiderationOptionId")
                        .HasColumnType("int");

                    b.Property<bool>("Thursday")
                        .HasColumnType("bit");

                    b.Property<bool>("TransportNeeded")
                        .HasColumnType("bit");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UpdaterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("bit");

                    b.HasKey("DayCarePackageId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("PackageId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TermTimeConsiderationOptionId");

                    b.HasIndex("UpdaterId");

                    b.ToTable("DayCarePackages");
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.DayCarePackageOpportunity", b =>
                {
                    b.Property<Guid>("DayCarePackageOpportunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DayCarePackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OpportunitiesNeedToAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpportunityLengthOptionId")
                        .HasColumnType("int");

                    b.Property<int>("OpportunityTimePerMonthOptionId")
                        .HasColumnType("int");

                    b.HasKey("DayCarePackageOpportunityId");

                    b.HasIndex("DayCarePackageId");

                    b.HasIndex("OpportunityLengthOptionId");

                    b.HasIndex("OpportunityTimePerMonthOptionId");

                    b.ToTable("DayCarePackageOpportunities");
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCare.HomeCarePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsFixedPeriod")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOngoingPeriod")
                        .HasColumnType("bit");

                    b.Property<bool>("IsThisAnImmediateService")
                        .HasColumnType("bit");

                    b.Property<bool>("IsThisuserUnderS117")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("StatusId");

                    b.ToTable("HomeCarePackage");
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCare.HomeCarePackageSlots", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<Guid>("HomeCarePackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NeedToAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrimaryInMinutes")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryInMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("TimeSlotShiftId")
                        .HasColumnType("int");

                    b.Property<string>("WhatShouldBeDone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TimeSlotShiftId");

                    b.ToTable("HomeCarePackageSlots");
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCare.HomeCareServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HomeCareServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 485, DateTimeKind.Unspecified).AddTicks(322), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 485, DateTimeKind.Unspecified).AddTicks(1952), new TimeSpan(0, 0, 0, 0, 0)),
                            ServiceName = "Personal Home Care",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 485, DateTimeKind.Unspecified).AddTicks(2361), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 485, DateTimeKind.Unspecified).AddTicks(2394), new TimeSpan(0, 0, 0, 0, 0)),
                            ServiceName = "Domestic Care",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 485, DateTimeKind.Unspecified).AddTicks(2402), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 485, DateTimeKind.Unspecified).AddTicks(2404), new TimeSpan(0, 0, 0, 0, 0)),
                            ServiceName = "Live-in Care",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 485, DateTimeKind.Unspecified).AddTicks(2406), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 485, DateTimeKind.Unspecified).AddTicks(2408), new TimeSpan(0, 0, 0, 0, 0)),
                            ServiceName = "Escort Care",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 485, DateTimeKind.Unspecified).AddTicks(2409), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 485, DateTimeKind.Unspecified).AddTicks(2412), new TimeSpan(0, 0, 0, 0, 0)),
                            ServiceName = "Night Owl",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 485, DateTimeKind.Unspecified).AddTicks(2413), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 485, DateTimeKind.Unspecified).AddTicks(2415), new TimeSpan(0, 0, 0, 0, 0)),
                            ServiceName = "Waking Nights",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 485, DateTimeKind.Unspecified).AddTicks(2416), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 485, DateTimeKind.Unspecified).AddTicks(2418), new TimeSpan(0, 0, 0, 0, 0)),
                            ServiceName = "Sleeping Nights",
                            UpdatorId = 1
                        });
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCare.HomeCareServiceTypeMinutes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HomeCareServiceTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSecondaryCarer")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HomeCareServiceTypeId");

                    b.ToTable("HomeCareServiceTypeMinutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HomeCareServiceTypeId = 1,
                            IsSecondaryCarer = false,
                            Label = "30 minutes",
                            Minutes = 30
                        },
                        new
                        {
                            Id = 2,
                            HomeCareServiceTypeId = 1,
                            IsSecondaryCarer = false,
                            Label = "45 minutes",
                            Minutes = 45
                        },
                        new
                        {
                            Id = 3,
                            HomeCareServiceTypeId = 1,
                            IsSecondaryCarer = false,
                            Label = "1 hour",
                            Minutes = 60
                        },
                        new
                        {
                            Id = 4,
                            HomeCareServiceTypeId = 1,
                            IsSecondaryCarer = false,
                            Label = "1 hour 15 minutes",
                            Minutes = 75
                        },
                        new
                        {
                            Id = 5,
                            HomeCareServiceTypeId = 1,
                            IsSecondaryCarer = false,
                            Label = "1 hour 30 minutes",
                            Minutes = 90
                        },
                        new
                        {
                            Id = 6,
                            HomeCareServiceTypeId = 1,
                            IsSecondaryCarer = false,
                            Label = "1 hour 45 minutes",
                            Minutes = 105
                        },
                        new
                        {
                            Id = 7,
                            HomeCareServiceTypeId = 1,
                            IsSecondaryCarer = false,
                            Label = "2 hours",
                            Minutes = 120
                        },
                        new
                        {
                            Id = 8,
                            HomeCareServiceTypeId = 1,
                            IsSecondaryCarer = true,
                            Label = "N/A",
                            Minutes = 0
                        },
                        new
                        {
                            Id = 9,
                            HomeCareServiceTypeId = 1,
                            IsSecondaryCarer = true,
                            Label = "30 minutes",
                            Minutes = 30
                        },
                        new
                        {
                            Id = 10,
                            HomeCareServiceTypeId = 1,
                            IsSecondaryCarer = true,
                            Label = "45 minutes",
                            Minutes = 45
                        },
                        new
                        {
                            Id = 11,
                            HomeCareServiceTypeId = 1,
                            IsSecondaryCarer = true,
                            Label = "1 hour",
                            Minutes = 60
                        },
                        new
                        {
                            Id = 12,
                            HomeCareServiceTypeId = 1,
                            IsSecondaryCarer = true,
                            Label = "1 hour 15 minutes",
                            Minutes = 75
                        },
                        new
                        {
                            Id = 13,
                            HomeCareServiceTypeId = 1,
                            IsSecondaryCarer = true,
                            Label = "1 hour 30 minutes",
                            Minutes = 90
                        },
                        new
                        {
                            Id = 14,
                            HomeCareServiceTypeId = 1,
                            IsSecondaryCarer = true,
                            Label = "1 hour 45 minutes",
                            Minutes = 105
                        },
                        new
                        {
                            Id = 15,
                            HomeCareServiceTypeId = 1,
                            IsSecondaryCarer = true,
                            Label = "2 hours",
                            Minutes = 120
                        },
                        new
                        {
                            Id = 16,
                            HomeCareServiceTypeId = 2,
                            IsSecondaryCarer = false,
                            Label = "30 minutes",
                            Minutes = 30
                        },
                        new
                        {
                            Id = 17,
                            HomeCareServiceTypeId = 2,
                            IsSecondaryCarer = false,
                            Label = "45 minutes",
                            Minutes = 45
                        },
                        new
                        {
                            Id = 18,
                            HomeCareServiceTypeId = 2,
                            IsSecondaryCarer = false,
                            Label = "1 hour",
                            Minutes = 60
                        },
                        new
                        {
                            Id = 19,
                            HomeCareServiceTypeId = 2,
                            IsSecondaryCarer = false,
                            Label = "1 hour 15 minutes",
                            Minutes = 75
                        },
                        new
                        {
                            Id = 20,
                            HomeCareServiceTypeId = 2,
                            IsSecondaryCarer = false,
                            Label = "1 hour 30 minutes",
                            Minutes = 90
                        },
                        new
                        {
                            Id = 21,
                            HomeCareServiceTypeId = 2,
                            IsSecondaryCarer = false,
                            Label = "1 hour 45 minutes",
                            Minutes = 105
                        },
                        new
                        {
                            Id = 22,
                            HomeCareServiceTypeId = 2,
                            IsSecondaryCarer = false,
                            Label = "2 hours",
                            Minutes = 120
                        },
                        new
                        {
                            Id = 23,
                            HomeCareServiceTypeId = 3,
                            IsSecondaryCarer = false,
                            Label = "30 minutes",
                            Minutes = 30
                        },
                        new
                        {
                            Id = 24,
                            HomeCareServiceTypeId = 3,
                            IsSecondaryCarer = false,
                            Label = "45 minutes",
                            Minutes = 45
                        },
                        new
                        {
                            Id = 25,
                            HomeCareServiceTypeId = 3,
                            IsSecondaryCarer = false,
                            Label = "1 hour",
                            Minutes = 60
                        },
                        new
                        {
                            Id = 26,
                            HomeCareServiceTypeId = 3,
                            IsSecondaryCarer = false,
                            Label = "1 hour 15 minutes",
                            Minutes = 75
                        },
                        new
                        {
                            Id = 27,
                            HomeCareServiceTypeId = 3,
                            IsSecondaryCarer = false,
                            Label = "1 hour 30 minutes",
                            Minutes = 90
                        },
                        new
                        {
                            Id = 28,
                            HomeCareServiceTypeId = 3,
                            IsSecondaryCarer = false,
                            Label = "1 hour 45 minutes",
                            Minutes = 105
                        },
                        new
                        {
                            Id = 29,
                            HomeCareServiceTypeId = 3,
                            IsSecondaryCarer = false,
                            Label = "2 hours",
                            Minutes = 120
                        },
                        new
                        {
                            Id = 30,
                            HomeCareServiceTypeId = 4,
                            IsSecondaryCarer = false,
                            Label = "30 minutes",
                            Minutes = 30
                        },
                        new
                        {
                            Id = 31,
                            HomeCareServiceTypeId = 4,
                            IsSecondaryCarer = false,
                            Label = "45 minutes",
                            Minutes = 45
                        },
                        new
                        {
                            Id = 32,
                            HomeCareServiceTypeId = 4,
                            IsSecondaryCarer = false,
                            Label = "1 hour",
                            Minutes = 60
                        },
                        new
                        {
                            Id = 33,
                            HomeCareServiceTypeId = 4,
                            IsSecondaryCarer = false,
                            Label = "1 hour 15 minutes",
                            Minutes = 75
                        },
                        new
                        {
                            Id = 34,
                            HomeCareServiceTypeId = 4,
                            IsSecondaryCarer = false,
                            Label = "1 hour 30 minutes",
                            Minutes = 90
                        },
                        new
                        {
                            Id = 35,
                            HomeCareServiceTypeId = 4,
                            IsSecondaryCarer = false,
                            Label = "1 hour 45 minutes",
                            Minutes = 105
                        },
                        new
                        {
                            Id = 36,
                            HomeCareServiceTypeId = 4,
                            IsSecondaryCarer = false,
                            Label = "2 hours",
                            Minutes = 120
                        });
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCare.TimeSlotShifts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("LinkedToHomeCareServiceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TimeSlotShiftName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeSlotTimeLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LinkedToHomeCareServiceTypeId");

                    b.ToTable("TimeSlotShifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(4918), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(4949), new TimeSpan(0, 0, 0, 0, 0)),
                            TimeSlotShiftName = "Morning",
                            TimeSlotTimeLabel = "08:00 - 10:00",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6263), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6268), new TimeSpan(0, 0, 0, 0, 0)),
                            TimeSlotShiftName = "Mid Morning",
                            TimeSlotTimeLabel = "10:00 - 12:00",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6306), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6307), new TimeSpan(0, 0, 0, 0, 0)),
                            TimeSlotShiftName = "Lunch",
                            TimeSlotTimeLabel = "12:00 - 14:00",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6308), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6309), new TimeSpan(0, 0, 0, 0, 0)),
                            TimeSlotShiftName = "Afternoon",
                            TimeSlotTimeLabel = "14:00 - 17:00",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6311), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6312), new TimeSpan(0, 0, 0, 0, 0)),
                            TimeSlotShiftName = "Evening",
                            TimeSlotTimeLabel = "17:00 - 20:00",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6313), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6315), new TimeSpan(0, 0, 0, 0, 0)),
                            TimeSlotShiftName = "Night",
                            TimeSlotTimeLabel = "20:00 - 22:00",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6316), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6317), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkedToHomeCareServiceTypeId = 5,
                            TimeSlotShiftName = "Night Owl",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6623), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6628), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkedToHomeCareServiceTypeId = 6,
                            TimeSlotShiftName = "Waking Nights",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6642), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 491, DateTimeKind.Unspecified).AddTicks(6643), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkedToHomeCareServiceTypeId = 7,
                            TimeSlotShiftName = "Sleeping Nights",
                            UpdatorId = 1
                        });
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCarePackageCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostPerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("HomeCarePackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HoursPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryCarer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecondaryCarer")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("HomeCarePackageCosts");
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.NursingCare.TypeOfNursingCareHome", b =>
                {
                    b.Property<int>("TypeOfCareHomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeOfCareHomeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeOfCareHomeId");

                    b.ToTable("TypesOfNursingCareHomes");

                    b.HasData(
                        new
                        {
                            TypeOfCareHomeId = 1,
                            TypeOfCareHomeName = "Nursing Care Type One"
                        },
                        new
                        {
                            TypeOfCareHomeId = 2,
                            TypeOfCareHomeName = "Nursing Care Type Two"
                        });
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.NursingCareAdditionalNeeds", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NeedToAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NursingCarePackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("OneOff")
                        .HasColumnType("bit");

                    b.Property<Guid>("UpdaterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Weekly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NursingCarePackageId");

                    b.ToTable("NursingCareAdditionalNeeds");
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.NursingCarePackages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsInterim")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLongStay")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnder52Weeks")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnder8Weeks")
                        .HasColumnType("bit");

                    b.Property<string>("NeedToAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfNursingCareHomeId")
                        .HasColumnType("int");

                    b.Property<int>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeOfNursingCareHomeId");

                    b.ToTable("NursingCarePackages");
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.OpportunityLengthOption", b =>
                {
                    b.Property<int>("OpportunityLengthOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OpportunityLengthOptionId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OptionName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TimeInMinutes")
                        .HasColumnType("int");

                    b.HasKey("OpportunityLengthOptionId");

                    b.HasIndex("OptionName")
                        .IsUnique()
                        .HasFilter("[OptionName] IS NOT NULL");

                    b.ToTable("OpportunityLengthOptions");

                    b.HasData(
                        new
                        {
                            OpportunityLengthOptionId = 1,
                            OptionName = "45 minutes",
                            TimeInMinutes = 45
                        },
                        new
                        {
                            OpportunityLengthOptionId = 2,
                            OptionName = "1 hour",
                            TimeInMinutes = 60
                        },
                        new
                        {
                            OpportunityLengthOptionId = 3,
                            OptionName = "1 hour 15 minutes",
                            TimeInMinutes = 75
                        });
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.OpportunityTimesPerMonthOption", b =>
                {
                    b.Property<int>("OpportunityTimePerMonthOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OpportunityTimePerMonthOptionId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OptionName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OpportunityTimePerMonthOptionId");

                    b.HasIndex("OptionName")
                        .IsUnique()
                        .HasFilter("[OptionName] IS NOT NULL");

                    b.ToTable("OpportunityTimesPerMonthOptions");

                    b.HasData(
                        new
                        {
                            OpportunityTimePerMonthOptionId = 1,
                            OptionName = "Daily"
                        },
                        new
                        {
                            OpportunityTimePerMonthOptionId = 2,
                            OptionName = "Weekly"
                        },
                        new
                        {
                            OpportunityTimePerMonthOptionId = 3,
                            OptionName = "Monthly"
                        });
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PackageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(7341), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(7349), new TimeSpan(0, 0, 0, 0, 0)),
                            PackageType = "Home Care Package",
                            Sequence = 0,
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(8444), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(8450), new TimeSpan(0, 0, 0, 0, 0)),
                            PackageType = "Residential Care Package",
                            Sequence = 0,
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(8481), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(8482), new TimeSpan(0, 0, 0, 0, 0)),
                            PackageType = "Day Care Package",
                            Sequence = 0,
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(8483), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(8484), new TimeSpan(0, 0, 0, 0, 0)),
                            PackageType = "Nursing Care Package",
                            Sequence = 0,
                            UpdatorId = 1
                        });
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.PackageStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PackageStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(3490), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(3518), new TimeSpan(0, 0, 0, 0, 0)),
                            StatusName = "New",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(4635), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(4640), new TimeSpan(0, 0, 0, 0, 0)),
                            StatusName = "Package Confirmation",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(4697), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(4699), new TimeSpan(0, 0, 0, 0, 0)),
                            StatusName = "Approved For Brokerage",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(4701), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(4702), new TimeSpan(0, 0, 0, 0, 0)),
                            StatusName = "Brokering",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(4703), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(4704), new TimeSpan(0, 0, 0, 0, 0)),
                            StatusName = "Supplier Sourced",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(4705), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(4706), new TimeSpan(0, 0, 0, 0, 0)),
                            StatusName = "Commercially Approved",
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(4708), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 502, DateTimeKind.Unspecified).AddTicks(4709), new TimeSpan(0, 0, 0, 0, 0)),
                            StatusName = "Contracted",
                            UpdatorId = 1
                        });
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.ResidentialCare.TypeOfResidentialCareHome", b =>
                {
                    b.Property<int>("TypeOfCareHomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeOfCareHomeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeOfCareHomeId");

                    b.ToTable("TypesOfResidentialCareHomes");

                    b.HasData(
                        new
                        {
                            TypeOfCareHomeId = 1,
                            TypeOfCareHomeName = "Residential Care Type One"
                        },
                        new
                        {
                            TypeOfCareHomeId = 2,
                            TypeOfCareHomeName = "Residential Care Type Two"
                        });
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.ResidentialCareAdditionalNeeds", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NeedToAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OneOff")
                        .HasColumnType("bit");

                    b.Property<Guid>("ResidentialCarePackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UpdaterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Weekly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ResidentialCarePackageId");

                    b.ToTable("ResidentialCareAdditionalNeeds");
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.ResidentialCarePackages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDischargePackage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpectedStayOver52Weeks")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImmediateReenablementPackage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRespiteCare")
                        .HasColumnType("bit");

                    b.Property<bool>("IsThisUserUnderS117")
                        .HasColumnType("bit");

                    b.Property<string>("NeedToAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfResidentialCareHomeId")
                        .HasColumnType("int");

                    b.Property<int>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeOfResidentialCareHomeId");

                    b.ToTable("ResidentialCarePackages");
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 503, DateTimeKind.Unspecified).AddTicks(833), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 503, DateTimeKind.Unspecified).AddTicks(840), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDefault = true,
                            RoleName = "Social Worker",
                            Sequence = 1,
                            UpdatorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 503, DateTimeKind.Unspecified).AddTicks(2268), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 503, DateTimeKind.Unspecified).AddTicks(2273), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDefault = false,
                            RoleName = "Broker",
                            Sequence = 2,
                            UpdatorId = 1
                        });
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.TermTimeConsiderationOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OptionId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OptionName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OptionId");

                    b.HasIndex("OptionName")
                        .IsUnique()
                        .HasFilter("[OptionName] IS NOT NULL");

                    b.ToTable("TermTimeConsiderationOptions");

                    b.HasData(
                        new
                        {
                            OptionId = 1,
                            OptionName = "N/A"
                        },
                        new
                        {
                            OptionId = 2,
                            OptionName = "Term Time"
                        },
                        new
                        {
                            OptionId = 3,
                            OptionName = "Holiday"
                        });
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HackneyId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Town")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aee45700-af9b-4ab5-bb43-535adbdcfb84"),
                            AddressLine1 = "Queens Gate",
                            CreatorId = 0,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 504, DateTimeKind.Unspecified).AddTicks(791), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 504, DateTimeKind.Unspecified).AddTicks(798), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Furkan",
                            HackneyId = 1111,
                            LastName = "Kayar",
                            PostCode = "W11",
                            RoleId = 1,
                            Town = "London",
                            UpdatorId = 0
                        },
                        new
                        {
                            Id = new Guid("1f825b5f-5c65-41fb-8d9e-9d36d78fd6d8"),
                            AddressLine1 = "Nairobi",
                            CreatorId = 0,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 504, DateTimeKind.Unspecified).AddTicks(3044), new TimeSpan(0, 0, 0, 0, 0)),
                            DateUpdated = new DateTimeOffset(new DateTime(2021, 4, 20, 16, 4, 12, 504, DateTimeKind.Unspecified).AddTicks(3050), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Duncan",
                            HackneyId = 4444,
                            LastName = "Okeno",
                            PostCode = "W11",
                            RoleId = 2,
                            Town = "Nairobi",
                            UpdatorId = 0
                        });
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.DayCarePackage", b =>
                {
                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.Clients", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.Users", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.PackageStatus", "PackageStatuses")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.TermTimeConsiderationOption", "TermTimeConsiderationOption")
                        .WithMany()
                        .HasForeignKey("TermTimeConsiderationOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.Users", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterId");
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.DayCarePackageOpportunity", b =>
                {
                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.DayCarePackage", "DayCarePackage")
                        .WithMany("DayCarePackageOpportunities")
                        .HasForeignKey("DayCarePackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.OpportunityLengthOption", "OpportunityLengthOption")
                        .WithMany()
                        .HasForeignKey("OpportunityLengthOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.OpportunityTimesPerMonthOption", "OpportunityTimesPerMonthOption")
                        .WithMany()
                        .HasForeignKey("OpportunityTimePerMonthOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCare.HomeCarePackage", b =>
                {
                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.Clients", "Clients")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.PackageStatus", "PackageStatuses")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCare.HomeCarePackageSlots", b =>
                {
                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCare.HomeCareServiceType", "Services")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCare.TimeSlotShifts", "TimeSlotShift")
                        .WithMany()
                        .HasForeignKey("TimeSlotShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCare.HomeCareServiceTypeMinutes", b =>
                {
                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCare.HomeCareServiceType", "HomeCareServiceType")
                        .WithMany("Minutes")
                        .HasForeignKey("HomeCareServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCare.TimeSlotShifts", b =>
                {
                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCare.HomeCareServiceType", "HomeCareServiceType")
                        .WithMany()
                        .HasForeignKey("LinkedToHomeCareServiceTypeId");
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCarePackageCost", b =>
                {
                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.HomeCare.HomeCareServiceType", "Services")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.NursingCareAdditionalNeeds", b =>
                {
                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.NursingCarePackages", null)
                        .WithMany("NursingCareAdditionalNeeds")
                        .HasForeignKey("NursingCarePackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.NursingCarePackages", b =>
                {
                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.Clients", "Clients")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.PackageStatus", "PackageStatuses")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.NursingCare.TypeOfNursingCareHome", "TypeOfCareHome")
                        .WithMany()
                        .HasForeignKey("TypeOfNursingCareHomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.ResidentialCareAdditionalNeeds", b =>
                {
                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.ResidentialCarePackages", null)
                        .WithMany("ResidentialCareAdditionalNeeds")
                        .HasForeignKey("ResidentialCarePackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.ResidentialCarePackages", b =>
                {
                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.Clients", "Clients")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.PackageStatus", "PackageStatuses")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.ResidentialCare.TypeOfResidentialCareHome", "TypeOfResidentialCareHome")
                        .WithMany()
                        .HasForeignKey("TypeOfResidentialCareHomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.Users", b =>
                {
                    b.HasOne("LBH.AdultSocialCare.Api.V1.Infrastructure.Entities.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
